// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<Record<string, any>>;

export function ConnectToTor(arg1:Array<string>,arg2:Array<string>,arg3:boolean,arg4:string):Promise<string>;

export function DisconnectFromTor():Promise<string>;

export function IsAutostartEnabled():Promise<boolean>;

export function LoadConfig():Promise<Record<string, any>>;

export function MinimizeToTray():Promise<void>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;

export function SaveConfig(arg1:string,arg2:Array<any>,arg3:boolean,arg4:string):Promise<string>;

export function ToggleAutostart(arg1:boolean):Promise<void>;
