// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ConnectToTor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectToTor'](arg1, arg2, arg3, arg4);
}

export function DisconnectFromTor() {
  return window['go']['main']['App']['DisconnectFromTor']();
}

export function IsAutostartEnabled() {
  return window['go']['main']['App']['IsAutostartEnabled']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OnBeforeClose(arg1) {
  return window['go']['main']['App']['OnBeforeClose'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4);
}

export function ToggleAutostart(arg1) {
  return window['go']['main']['App']['ToggleAutostart'](arg1);
}
