// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToTor(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<string>;

export function DisconnectFromTor():Promise<string>;
