// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ConnectToTor(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToTor'](arg1, arg2, arg3);
}

export function DisconnectFromTor() {
  return window['go']['main']['App']['DisconnectFromTor']();
}
